
# 服务端口
server:
  port: 9527
  servlet:
    context-path: /dobby

spring:
  application:
    name: dobby
  profiles:
    active: dev

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.albusxing.dobby.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      insert-strategy: NOT_EMPTY
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


# 日志
logging:
  level:
    com.albusxing.mapper: debug

jwt:
  token:
    # 秘钥
    secretKey: MTE1NGU1NjkwNjk0NTYzMzU2ZjI0ZDljMjQ2NWQ3MjYxZTZkZGFkN2IxOTA5NWFmYTRiMjU3YzlkNmYyYmUzYzM5YWRkYTE1MjAxNjQ5MzRmZDNkYTEyMjFmMzVmZDJhYTg3ODk2ZGM3MGEwNTI4YTMzYzc0NjM2NTMzNDdmNjE
    # token有效时长，7天，单位秒
    expiration: 604800
    headerName: token
    issuer: albusxing
    authKey: clientCode

management:
  #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

mq:
  exchange: dobby-exchange
  queue: dobby-queue
  routingKey: dobby-routing-key


xxl:
  job:
    ### 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: ''
    ### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address: ''
      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: xxl-job-executor-sample
      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip: ''
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: /data/applogs/xxl-job/jobhandler
      ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999

